### ISSUE TITLE
Backup Emails have stopped

### ISSUE THREAD

**Issue by Graham9999** [sethrandall/f5backup#5]
Our backups are continuing to process, however the emails have stopped.  Is anyone able to guide me in the direction to find logs to track down what may be the problem?

**Comment by sethrandall** [comment]
There are log files in /var/log and in /opt/f5backup/log. There might be something in there. If not, let me know and I will dig deeper.

**Comment by Graham9999** [comment]
I have since found out that a previous engineer wrote a script for sending out an email grabbing the log file details and emailing it out, so we didn't have to manually check every morning.  Apologies, this isn't part of the github project.
